CREATE TABLE KH_STUDENT(
	STD_NO NUMBER PRIMARY KEY,
	STD_NAME NVARCHAR2(5) NOT NULL,
	STD_AGE NUMBER NOT NULL,
	MAJOR NVARCHAR2(10) NOT NULL,
	ENT_DATE DATE DEFAULT SYSDATE
);

CREATE SEQUENCE STD_NO NOCACHE;

INSERT INTO KH_STUDENT VALUES(STD_NO.NEXTVAL, '유저일', 21, '화학', DEFAULT );
INSERT INTO KH_STUDENT VALUES(STD_NO.NEXTVAL, '유저이', 22, '수학', DEFAULT );
INSERT INTO KH_STUDENT VALUES(STD_NO.NEXTVAL, '유저삼', 23, '화학', DEFAULT );
INSERT INTO KH_STUDENT VALUES(STD_NO.NEXTVAL, '유저사', 24, '물리', DEFAULT );

SELECT * FROM KH_STUDENT;

DELETE KH_STUDENT
WHERE STD_NO = 5;


SELECT STD_NO, STD_NAME, STD_AGE, MAJOR,
TO_CHAR(ENT_DATE, 'YYYY"년" MM"월" DD"일"') ENT_DATE
FROM KH_STUDENT;


SELECT STD_NAME
FROM KH_STUDENT
WHERE MAJOR = '화학';